# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autodrill/ui/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(698, 653)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.boardDrillsWidget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boardDrillsWidget.sizePolicy().hasHeightForWidth())
        self.boardDrillsWidget.setSizePolicy(sizePolicy)
        self.boardDrillsWidget.setObjectName(_fromUtf8("boardDrillsWidget"))
        self.gridLayout.addWidget(self.boardDrillsWidget, 0, 0, 2, 1)
        self.cameraWidget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraWidget.sizePolicy().hasHeightForWidth())
        self.cameraWidget.setSizePolicy(sizePolicy)
        self.cameraWidget.setObjectName(_fromUtf8("cameraWidget"))
        self.gridLayout.addWidget(self.cameraWidget, 0, 1, 1, 1)
        self.gridLayout_zoom = QtGui.QGridLayout()
        self.gridLayout_zoom.setObjectName(_fromUtf8("gridLayout_zoom"))
        self.verticalSlider_cameraZoom = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_cameraZoom.setMinimum(10)
        self.verticalSlider_cameraZoom.setMaximum(100)
        self.verticalSlider_cameraZoom.setSingleStep(1)
        self.verticalSlider_cameraZoom.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_cameraZoom.setObjectName(_fromUtf8("verticalSlider_cameraZoom"))
        self.gridLayout_zoom.addWidget(self.verticalSlider_cameraZoom, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_zoom.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 58, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_zoom.addItem(spacerItem, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_zoom, 0, 2, 1, 1)
        self.treeWidget_holes = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidget_holes.setObjectName(_fromUtf8("treeWidget_holes"))
        self.treeWidget_holes.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout.addWidget(self.treeWidget_holes, 1, 1, 1, 1)
        self.groupBox_trafo = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_trafo.setObjectName(_fromUtf8("groupBox_trafo"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_trafo)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_addPoint = QtGui.QPushButton(self.groupBox_trafo)
        self.pushButton_addPoint.setObjectName(_fromUtf8("pushButton_addPoint"))
        self.verticalLayout.addWidget(self.pushButton_addPoint)
        self.pushButton_removeLast = QtGui.QPushButton(self.groupBox_trafo)
        self.pushButton_removeLast.setEnabled(False)
        self.pushButton_removeLast.setObjectName(_fromUtf8("pushButton_removeLast"))
        self.verticalLayout.addWidget(self.pushButton_removeLast)
        self.pushButton_removeAll = QtGui.QPushButton(self.groupBox_trafo)
        self.pushButton_removeAll.setEnabled(False)
        self.pushButton_removeAll.setObjectName(_fromUtf8("pushButton_removeAll"))
        self.verticalLayout.addWidget(self.pushButton_removeAll)
        self.label_2 = QtGui.QLabel(self.groupBox_trafo)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox_trafo)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.label_trafoPoints = QtGui.QLabel(self.groupBox_trafo)
        self.label_trafoPoints.setObjectName(_fromUtf8("label_trafoPoints"))
        self.horizontalLayout.addWidget(self.label_trafoPoints)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 138, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.groupBox_trafo, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 698, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_loadDrillFile = QtGui.QAction(MainWindow)
        self.action_loadDrillFile.setObjectName(_fromUtf8("action_loadDrillFile"))
        self.action_dialogDrills = QtGui.QAction(MainWindow)
        self.action_dialogDrills.setObjectName(_fromUtf8("action_dialogDrills"))
        self.action_dialogCamera = QtGui.QAction(MainWindow)
        self.action_dialogCamera.setObjectName(_fromUtf8("action_dialogCamera"))
        self.action_writeGCode = QtGui.QAction(MainWindow)
        self.action_writeGCode.setObjectName(_fromUtf8("action_writeGCode"))
        self.action_dialogDrillParameter = QtGui.QAction(MainWindow)
        self.action_dialogDrillParameter.setObjectName(_fromUtf8("action_dialogDrillParameter"))
        self.menuFile.addAction(self.action_loadDrillFile)
        self.menuFile.addAction(self.action_writeGCode)
        self.menuSettings.addAction(self.action_dialogDrills)
        self.menuSettings.addAction(self.action_dialogDrillParameter)
        self.menuSettings.addAction(self.action_dialogCamera)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "auto drill", None))
        self.label_3.setText(_translate("MainWindow", "Zoom", None))
        self.groupBox_trafo.setTitle(_translate("MainWindow", "Transformation", None))
        self.pushButton_addPoint.setText(_translate("MainWindow", "Add Selected Point", None))
        self.pushButton_removeLast.setText(_translate("MainWindow", "Remove Last Point", None))
        self.pushButton_removeAll.setText(_translate("MainWindow", "Remove All", None))
        self.label_2.setText(_translate("MainWindow", "Please select 3 or 4 points.", None))
        self.label.setText(_translate("MainWindow", "Points used:", None))
        self.label_trafoPoints.setText(_translate("MainWindow", "0", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "S&ettings", None))
        self.action_loadDrillFile.setText(_translate("MainWindow", "&Load Drill File", None))
        self.action_dialogDrills.setText(_translate("MainWindow", "&Drills", None))
        self.action_dialogCamera.setText(_translate("MainWindow", "&Camera Settings", None))
        self.action_writeGCode.setText(_translate("MainWindow", "&Write G-Code Files", None))
        self.action_dialogDrillParameter.setText(_translate("MainWindow", "Drill Parameter", None))

